// TODO: get privileges from DB
export enum Privilege {
  POST_CREATE = 'POST_CREATE',
  POST_UPDATE = 'POST_UPDATE',
  POST_DELETE = 'POST_DELETE',
  USER_DELETE = 'USER_DELETE',
  USER_UPDATE = 'USER_UPDATE',
  USER_UPDATE_SELF = 'USER_UPDATE',
  USER_GET = 'USER_GET',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_GET = 'ROLE_GET',
  PRIVILEGE_CREATE = 'PRIVILEGE_CREATE',
  PRIVILEGE_UPDATE = 'PRIVILEGE_UPDATE',
  PRIVILEGE_DELETE = 'PRIVILEGE_DELETE',
  PRIVILEGE_GET = 'PRIVILEGE_GET',
}
